[package]
name = "rust_sqwar"
version = "0.1.0"
authors = ["rekz"]

[dependencies]
amethyst = "0.9.0"
specs-derive = "*"
serde = "1.0"
serde_derive = "1.0"

[features]
nightly = [
    "amethyst/nightly",
]
