[package]
name = "rust_sqwar"
version = "0.1.0"
authors = ["rekz"]
edition = "2018"

[dependencies]
amethyst = "0.10.0"
specs-derive = "*"
serde = "1.0"
serde_derive = "1.0"
rand = "0.6"

[features]
nightly = [
    "amethyst/nightly",
]
sdl_controller = [
    "amethyst/sdl_controller",
]
